---
title: "Fatal Police Shootings Analysis"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll

---

```{r setup, include=FALSE}

#packages ----
library(dplyr)
library(ggplot2)
library(shiny)
library(highcharter)
library(dygraphs)
library(plotly)
library(flexdashboard)
library(lubridate)
library(forecast)

#loads and formats data----

#shooting data
data <- read.csv("https://raw.githubusercontent.com/washingtonpost/data-police-shootings/master/fatal-police-shootings-data.csv")
data$date <- ymd(data$date)
data$age <- as.numeric(data$age)
data$state.flag <- "other"
data$state.flag[data$state == "PA"] <- "PA"
data$state.flag <- as.factor(data$state.flag)
data$city.flag <- "other"
data$city.flag[data$city== "Philadelphia"] <- "PHL"
data$city.flag <- as.factor(data$city.flag)
data$month <- month(data$date, label = TRUE)
data$year <- year(data$date)
data$year <- as.factor(data$year)
data$day <- wday(data$date, label = TRUE, abbr = TRUE)
data$count <- 1
data$age[is.na(data$age)] <- 0

#re-codes race as white, black hispanic, other
data$race2 <- "Other"
data$race2[data$race == "W"] <- "White"
data$race2[data$race == "B"] <- "Black"
data$race2[data$race == "H"] <- "Hispanic"
data$race2[data$race == " "] <- "Unknown"
data$race2 <- as.factor(data$race2)

#creates age buckets
data$age2 <- "Under 18"
data$age2[18 <= data$age & data$age < 30] <- "18 to 29"
data$age2[30 <= data$age & data$age < 45] <- "30 to 44"
data$age2[45 <= data$age] <- "45 and Older"
data$age2[data$age == 0] <- "Unknown"
data$age2 <- as.factor(data$age2)

#loads and checks structure
#View(data)
#str(data)

#state population data
states <- read.csv("http://www.census.gov/popest/data/state/totals/2015/tables/NST-EST2015-01.csv", header = FALSE)
states <- states[-c(1, 2, 3, 4, 5, 6, 7, 8, 9, 61, 62, 63, 64, 65, 66, 67), -c(2,3,4,5,6,7,8)] #removes unwanted rows and columns, keeps only 2015 population and state name
names(states)[1] <- "state"
names(states)[2] <- "pop"
states$state <- sub('.', '', states$state) #removes "." at beginning of state names
states$pop <- gsub(',', '', states$pop) #removes commas from population column
states$state <- state.abb[match(states$state,state.name)] #adds state abbreviations
states[9,1] <- "DC" #Adds Washington DC abbreviation
states$state <- as.factor(states$state)
states$pop <- as.numeric(states$pop)

#loads and checks structure
#View(states)
#str(states)

#joins shooting and population data
data <- left_join(data, states, by = "state")
data$state <- as.factor(data$state)
#str(data)

#creates dataframe of list of dates to fill in date gaps
date.ref <- data.frame(date=seq(as.Date("2015-01-01"), as.Date("2016-01-15"), by="days"))
date.ref$date <- ymd(date.ref$date)

#joins data and date.ref dataframes and replaces na with 0's
data <- merge(data,date.ref,by.x='date',by.y='date',all.x=T,all.y=T)
data$count[is.na(data$count)] <- 0



```

-----------------------------------------------------------------------

### Fatal Shootings by Police by State (2015)
```{r,echo = T, fig.width=10, fig.height=7}
#plot of shootings by state
hchart(subset(data$state, data$year == "2015"), name = "Shootings")
```


-----------------------------------------------------------------------

### Shootings by police by Race (2015)

```{r, echo = T}
#plot of shootings by race
hchart(subset(data$race2, data$year == "2015"), name = "2015 Shootings", colorByPoint = T)
```

### Forecast of Fatal police Shootings

```{r,echo = T}
monthly <- data %>% group_by(year, month) %>% summarise(total = n())
total <- ts(monthly$total, frequency = 12)
airforecast <- forecast(auto.arima(total), level = 95)
hchart(airforecast) %>%
  hc_add_theme(hc_theme_smpl())
```

